export const projects = [
  {
    key: 'prephouse',
    title: 'Prephouse',
    meta: 'Automated Interview Feedback System',
    description: [].join(' '),
    labels: [
      'React',
      'Redux',
      'Python',
      'Flask',
      'gRPC',
      'NumPy',
      'Pandas',
      'OpenCV',
      'PostgreSQL',
    ],
    repoUrl: 'https://github.com/Sapphire-Labs/factibly',
    appUrl: 'https://www.factibly.com',
  },
  {
    key: 'factibly',
    title: 'Factibly',
    meta: 'Crowd-Sourced Fact Checker',
    description: [
      'We used TypeScript and React on the front-end and Django on the back-end, with Apollo as',
      'the client for our custom GraphQL queries and mutations. We also explored other various',
      'aspects of web development, such as internationalization, accessibility (WCAG 2.1) and',
      'search engine optimizations (SEO).',
    ].join(' '),
    labels: [
      'React',
      'Redux',
      'Apollo Client',
      'Python',
      'Django',
      'Graphene',
      'Relay',
      'PostgreSQL',
    ],
    repoUrl: 'https://github.com/Sapphire-Labs/factibly',
    appUrl: 'https://www.factibly.com',
  },
  {
    key: 'budgetter',
    title: 'Budgetter',
    meta: 'Android Budget Tracker',
    description: [
      'I developed a Material-themed Android app with modern Jetpack libraries,',
      "dependency injection and Airbnb's Mavericks framework. With the app, you",
      'can keep track of your individual transactions either by manually filling out',
      'the details of each transaction or by using the custom barcode scanner.',
      'Then, at the end of every week, you can obtain a summary of how much',
      "you've spent relative to your budget for that week.",
    ].join(' '),
    labels: ['Android SDK', 'Mavericks', 'Cloud Firestore'],
    repoUrl: 'https://github.com/JadonFan/Budgeting',
  },
  {
    key: 'bestbooks',
    title: 'BestBooks',
    meta: 'NYTimes Bestsellers Aggregator',
    description: [
      'For all of you bookworms out there, this website gives you a neat feed with the',
      'details of the latest NYTimes bestsellers in each category. This simple yet',
      'useful website was my first and rather successful attempt at utilizing the Ruby',
      'on Rails framework on the back-end.',
    ].join(' '),
    labels: ['React', 'Redux', 'Ruby', 'Ruby on Rails'],
    repoUrl: 'https://github.com/JadonFan/NYTimes_Books',
  },
  {
    title: 'EduPlan',
    meta: 'Student Life Planner',
    description: [
      'This desktop Java app is designed by students, for students, to plan your university',
      'life, such as your courses for the next academic term and your daily schedule.',
      "Your university life may get busy but it shouldn't need to be difficult to manage.",
    ].join(' '),
    labels: [
      'JavaFX',
      'JDBC',
      'MySQL',
      'AWS',
    ],
    repoUrl: 'https://github.com/JadonFan/Planner',
  },
  {
    key: 'firstgame',
    title: 'First Game',
    meta: 'Family-Friendly Casual Mobile Games',
    description: [
      'This Android app may seem basic, but it helped me a lot with getting',
      'started in Android development.',
    ].join(' '),
    labels: ['Android SDK'],
    repoUrl: 'https://github.com/JadonFan/Casual-Games',
  },
];
