export const skills = {
  web: [
    'JavaScript',
    'TypeScript',
    'React',
    'Redux',
    'Jest',
    'Enzyme',
    'Apollo Client',
  ],
  android: [
    'Kotlin',
    'Java',
    'Gradle',
    'Jetpack Architecture Components',
    'Material Design Components (MDC)',
    'Hilt/Dagger',
    'Retrofit',
    'Apollo Client',
    'Room',
    'Jetpack Navigation',
    'JUnit',
    'Mockito',
    'Espresso',
  ],
  backend: [
    'Python',
    'Ruby',
    'Java',
    'Ruby on Rails',
    'Rake',
    'RSpec',
    'Django',
    'Tornado',
    'PostgreSQL',
    'MongoDB',
    'gRPC',
  ],
  cloud: [
    'Amazon EC2',
    'Amazon S3',
    'Amazon RDS',
    'Amazon CloudFront',
    'AWS Fargate',
    'AWS Elastic Beanstalk',
  ],
  tools: [
    'Git',
    'Treasure Data',
    'CircleCI',
    'Jenkins',
    'JMeter',
  ],
  system: [
    'Bash',
    'C',
    'C++',
  ],
};
